---
id: ListHeaders
name: ListHeaders
full: List headers parsing library
description: >
  The Horde_ListHeaders library parses Mailing List Headers as defined in RFC
  2369 & RFC 2919.
list: dev
type: library
